model:
  name: 'resnet50_fc512'

data:
  type: 'image'
  height: 256
  width: 128
  sources: ['soccernetv3']
  targets: ['soccernetv3', 'soccernetv3_test', 'soccernetv3_challenge']
  workers: 4

soccernetv3:
  training_subset: 0.005

sampler:
  train_sampler: RandomIdentitySampler # sampler for source train loader
  train_sampler_t: RandomIdentitySampler # sampler for target train loader
  num_instances: 4 # number of instances per identity for RandomIdentitySampler

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 0.5
    weight_x: 0.5

train:
  batch_size: 32
  print_freq: 10
  max_epoch: 10

test:
  ranks: [1]
  export_distmat: True